DROP TABLE t_estab_saude CASCADE CONSTRAINTS;

DROP TABLE t_leitos CASCADE CONSTRAINTS;

DROP TABLE t_municipios CASCADE CONSTRAINTS;

DROP TABLE t_populacao CASCADE CONSTRAINTS;

DROP TABLE t_prof_saude CASCADE CONSTRAINTS;